### ISSUE TITLE
subgroup scenarios use wrong alpha to calibrate scenarios[BUG]

### ISSUE THREAD

**Issue by floatofmath** [SimNPH/SimNPH#124]
**Describe the bug**
hazard_subgroup_from_PH_effect_size has target_alpha set to 0.05 which is not in line with one-sided tests at level 0.025, consequently the results do not reach target power. The sample size computation is correct, however, the default value is at odds with the usual one-sided level. This results in miscalibrated scenarios in the set_paramaters_subgroup script which uses the default.

**Expected behavior**
We should fix the docu of target_alpha to make it explicit that this is one-sided, if any default is used it should be 0.025

**Comment by floatofmath** [comment]
I have fixed the code of the functions in presentation_fk

**Comment by TobiasFellinger** [comment]
I have also fixed it in sims_full_bugfix. I'll have to be careful when merging.
