### ISSUE TITLE
[BUG] check why dplyr::filter is masked by stats::filter on package load

### ISSUE THREAD

**Issue by floatofmath** [SimNPH/SimNPH#152]
**Describe the bug**
Reknitting the study report I encountered errors with dplyr::filter being masked by stats::filter. Maybe the package loading order is not right. This is package internaly, I could not fix the problem by loading dplyr in my session. Had to fix the function call to dplyr::filter in tabset_loop to make it work. As we rely heavily on filters in the remaining package we should check whether this is an issue anywhere else. This was on brach merge_report.

**Comment by TobiasFellinger** [comment]
Removed superfluous import of `stats::filter` @floatofmath please check if the report can be built now with the package from the `merge_report` branch.
